// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/mazrean/separated-webshell/api"
	"github.com/mazrean/separated-webshell/domain"
	"github.com/mazrean/separated-webshell/repository"
	"github.com/mazrean/separated-webshell/repository/badger"
	"github.com/mazrean/separated-webshell/service"
	"github.com/mazrean/separated-webshell/ssh"
	"github.com/mazrean/separated-webshell/store"
	"github.com/mazrean/separated-webshell/store/gomap"
	"github.com/mazrean/separated-webshell/workspace"
	"github.com/mazrean/separated-webshell/workspace/docker"
)

// Injectors from wire.go:

func InjectServer(apiKey APIKey, connectionLimiter *domain.ConnectionLimiter, badgerDir BadgerDir, maxConnPerUser int64, apiConfig api.Config, welcome WelcomeMessage) (*Server, func(), error) {
	workspace, err := docker.NewWorkspace(maxConnPerUser)
	if err != nil {
		return nil, nil, err
	}
	gomapWorkspace := gomap.NewWorkspace()
	dbConfig := provideDBConfig(badgerDir)
	db, cleanup, err := newDBFromConfig(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	transaction := badger.NewTransaction(db)
	user := badger.NewUser(db)
	setup := service.NewSetup(workspace, gomapWorkspace, transaction, user)
	serviceUser := service.NewUser(workspace, gomapWorkspace, user, transaction)
	userConfig := provideUserConfig(apiKey)
	apiUser := newUserFromConfig(serviceUser, userConfig)
	apiAPI := api.NewAPI(apiUser, apiConfig)
	workspaceConnection := docker.NewWorkspaceConnection()
	pipeConfig := providePipeConfig(welcome)
	pipe := newPipeFromConfig(gomapWorkspace, workspaceConnection, workspace, connectionLimiter, pipeConfig)
	sshSSH := ssh.NewSSH(serviceUser, pipe)
	server, err := NewServer(setup, apiAPI, sshSSH)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

type BadgerDir string

type APIKey string

type WelcomeMessage string

var (
	transactionBind         = wire.Bind(new(repository.ITransaction), new(*badger.Transaction))
	storeWorkspaceBind      = wire.Bind(new(store.IWorkspace), new(*gomap.Workspace))
	repositoryUserBind      = wire.Bind(new(repository.IUser), new(*badger.User))
	workspaceBind           = wire.Bind(new(workspace.IWorkspace), new(*docker.Workspace))
	workspaceConnectionBind = wire.Bind(new(workspace.IWorkspaceConnection), new(*docker.WorkspaceConnection))
	serviceUserBind         = wire.Bind(new(service.IUser), new(*service.User))
	servicePipeBind         = wire.Bind(new(service.IPipe), new(*service.Pipe))
)

type Server struct {
	*service.Setup
	*api.API
	*ssh.SSH
}

func NewServer(setup *service.Setup, a *api.API, s *ssh.SSH) (*Server, error) {
	return &Server{
		Setup: setup,
		API:   a,
		SSH:   s,
	}, nil
}

func provideAPIKeyForUser(key APIKey) string {
	return string(key)
}

func provideBadgerDirForDB(dir BadgerDir) string {
	return string(dir)
}

func provideWelcomeForPipe(msg WelcomeMessage) string {
	return string(msg)
}

type DBConfig struct {
	Dir string
}

func provideDBConfig(dir BadgerDir) *DBConfig {
	return &DBConfig{Dir: string(dir)}
}

func newDBFromConfig(config *DBConfig) (*badger.DB, func(), error) {
	return badger.NewDB(config.Dir)
}

type PipeConfig struct {
	Welcome string
}

func providePipeConfig(msg WelcomeMessage) *PipeConfig {
	return &PipeConfig{Welcome: string(msg)}
}

func newPipeFromConfig(sw store.IWorkspace, wwc workspace.IWorkspaceConnection, ww workspace.IWorkspace, cl *domain.ConnectionLimiter, config *PipeConfig) *service.Pipe {
	return service.NewPipe(sw, wwc, ww, cl, config.Welcome)
}

type UserConfig struct {
	APIKey string
}

func provideUserConfig(key APIKey) *UserConfig {
	return &UserConfig{APIKey: string(key)}
}

func newUserFromConfig(u *service.User, config *UserConfig) *api.User {
	return api.NewUser(u, config.APIKey)
}
