// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=mock_service/mock_user.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	values "github.com/mazrean/separated-webshell/domain/values"
	gomock "go.uber.org/mock/gomock"
)

// MockIUser is a mock of IUser interface.
type MockIUser struct {
	ctrl     *gomock.Controller
	recorder *MockIUserMockRecorder
	isgomock struct{}
}

// MockIUserMockRecorder is the mock recorder for MockIUser.
type MockIUserMockRecorder struct {
	mock *MockIUser
}

// NewMockIUser creates a new mock instance.
func NewMockIUser(ctrl *gomock.Controller) *MockIUser {
	mock := &MockIUser{ctrl: ctrl}
	mock.recorder = &MockIUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUser) EXPECT() *MockIUserMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockIUser) Auth(ctx context.Context, name values.UserName, password values.Password) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, name, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockIUserMockRecorder) Auth(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockIUser)(nil).Auth), ctx, name, password)
}

// New mocks base method.
func (m *MockIUser) New(ctx context.Context, name values.UserName, password values.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", ctx, name, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockIUserMockRecorder) New(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIUser)(nil).New), ctx, name, password)
}

// ResetContainer mocks base method.
func (m *MockIUser) ResetContainer(ctx context.Context, userName values.UserName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetContainer", ctx, userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetContainer indicates an expected call of ResetContainer.
func (mr *MockIUserMockRecorder) ResetContainer(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetContainer", reflect.TypeOf((*MockIUser)(nil).ResetContainer), ctx, userName)
}
